### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by JaviLopez-BerkeleyCollege** [AtomLinter/linter-htmlhint#170]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Education
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package 1.4.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At C:\Users\javier-lopez3\AppData\Local\atom\app-1.22.1\resources\app\static\<embedded>:1

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at installLinterHtmlhintDeps (/packages/linter-htmlhint/lib/index.js:73:9)
```

### Commands

```
     -1:27.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
 13x -0:46.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-bootstrap4 1.4.0 
atom-html-templates 0.1.3 
atom-javascript-console-snippets 0.10.0 
atom-live-server 2.2.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
best-js-snippets 4.1.0 
bootstrap-vue-snippets 0.4.0 
busy-signal 1.4.3 
css-snippets 1.1.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.14 
highlight-selected 0.13.1 
html-head-snippets 0.2.0 
html-to-css 0.2.2 
indent-guide-improved 1.4.13 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-csslint 2.0.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-jslint 11.1.0 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
pigments 0.40.2 
react-es7-snippets 0.3.13 
react-snippets 1.0.1 
rest-client 1.3.1 
seti-icons 1.5.4 
template-generator 0.15.1 
tree-view-panes 0.3.7 
turbo-javascript 1.4.0 
```

**Comment by Arcanemagus** [comment]
Atom sometimes fails to install all dependencies, please try re-installing the package.
