### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-callsite'

### ISSUE THREAD

**Issue by Larend** [AtomLinter/linter-htmlhint#179]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package 1.4.0

### Stack Trace

Uncaught Error: Cannot find module 'sb-callsite'

```
At module.js:472

Error: Cannot find module 'sb-callsite'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-htmlhint/node_modules/atom-package-path/lib/index.js:9:18)
    at /packages/linter-htmlhint/node_modules/atom-package-path/lib/index.js:37:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-csslint/node_modules/atom-package-deps/lib/index.js:50:24)
    at /packages/linter-csslint/node_modules/atom-package-deps/lib/index.js:83:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at installLinterUIDefaultDeps (/packages/linter-ui-default/lib/index.js:28:9)
```

### Commands

```
     -0:36.2.0 core:paste (input.hidden-input)
     -0:29 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
aligner-php 1.2.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.32.5 
autocomplete-bash-builtins 0.3.5 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.21 
git-blame 1.7.0 
git-plus 7.10.2 
git-time-machine 2.1.0 
highlight-line 0.12.0 
ide-bash 1.0.11 
intentions 1.1.5 
linter 2.2.0 
linter-checkbashisms 0.1.5 
linter-csslint 2.0.1 
linter-eslint 8.4.1 
linter-htmlhint 1.4.0 
linter-js-yaml 1.3.0 
linter-jshint 3.1.8 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-scss-lint 3.1.1 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
livereload 0.4.4 
minimap 4.29.8 
open-bash-git 2.3.3 
project-manager 3.3.6 
remote-ftp 2.2.0 
script 3.18.1 
wordpress-api 1.2.2 
```

**Comment by Arcanemagus** [comment]
Sub-dependency failures like this are an issue with `apm`, nothing that we can do about that here unfortunately.

Please try updating the package, or installing an update.
