### ISSUE TITLE
Uncaught Error: Cannot find module 'tmp'

### ISSUE THREAD

**Issue by RafaelLinux** [AtomLinter/linter-htmlhint#183]
[Enter steps to reproduce:]

1. Just open ATOM
2. Error is showed in a float window

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: "openSUSE Leap
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package 1.4.0

### Stack Trace

Uncaught Error: Cannot find module 'tmp'

```
At module.js:545

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-htmlhint/node_modules/atom-linter/lib/helpers.js:23:12)
    at /packages/linter-htmlhint/node_modules/atom-linter/lib/helpers.js:139:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-htmlhint/node_modules/atom-linter/lib/index.js:139:16)
    at /packages/linter-htmlhint/node_modules/atom-linter/lib/index.js:329:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/packages/linter-htmlhint/lib/index.js:52:37)
    at installLinterHtmlhintDeps (/packages/linter-htmlhint/lib/index.js:75:7)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-css-comb 3.3.1 
atom-notifier 0.7.0 
atom-webstorm-ui-theme 0.0.1 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-modules 2.1.0 
autocomplete-php 0.3.7 
autoprefixer 3.7.1 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
color-picker 2.3.0 
dash-ui 0.4.4 
escape-utils 0.5.3 
fancy-bracket-matcher 2.1.0 
file-icons 2.1.22 
fold-comments 0.6.0 
fold-functions 0.5.0 
fold-lines 0.2.2 
fonts 3.1.0 
fox-syntax-theme 1.2.0 
glowing-cursor 0.1.2 
hey-pane 1.1.0 
intentions 1.1.5 
language-rpm-spec 0.16.0 
language-svg 0.9.2 
linter 2.2.0 
linter-doiuse 0.2.3 
linter-htmlhint 1.4.0 
linter-jshint 3.1.8 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-pigments 0.2.2 
nms-color-bracket 0.1.0 
open-recent 5.0.0 
php-cs-fixer 4.1.1 
php-hyperclick 1.2.1 
php-integrator-annotations 1.2.0 
pigments 0.40.2 
power-effects 0.4.0 
remember-file-positions 0.2.3 
remember-folds 0.3.0 
remote-edit2 3.0.0 
sexy-dark-theme 0.1.0 
sombre-theme 1.0.0 
svg-preview 0.12.1 
theme-alien-syntax 0.6.0 
tron-theme 0.3.3 
```

**Comment by Arcanemagus** [comment]
Sub-dependency failures like this are an issue with `apm`, nothing that we can do about that here unfortunately.
