### ISSUE TITLE
Uncaught Error: Cannot find module 'core-js/library/fn/promise'

### ISSUE THREAD

**Issue by catrina** [AtomLinter/linter-htmlhint#210]
[Enter steps to reproduce:]

1. ... update linter-htmlhint

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package 1.6.1

### Stack Trace

Uncaught Error: Cannot find module 'core-js/library/fn/promise'

```
At module.js:545

Error: Cannot find module 'core-js/library/fn/promise'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/linter-htmlhint/node_modules/babel-runtime/core-js/promise.js:1:186)
    at /packages/linter-htmlhint/node_modules/babel-runtime/core-js/promise.js:2:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/linter-htmlhint/node_modules/tiny-promisify/dist/index.js:3:16)
    at /packages/linter-htmlhint/node_modules/tiny-promisify/dist/index.js:52:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at loadDeps (/packages/linter-htmlhint/lib/index.js:68:21)
    at installLinterHtmlhintDeps (/packages/linter-htmlhint/lib/index.js:85:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
intentions 1.1.5 
lint 0.0.1 
linter 2.3.0 
linter-htmlhint 1.6.1 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-ui-default 1.7.1 
```

**Comment by Arcanemagus** [comment]
It looks like a module _deep_ in the dependency tree failed to install. Can you try re-installing the package to see if `apm` will work correctly this time?

**Comment by kihikasamuel** [comment]
Faced this issue too and I did downgrade the 'core-js' from 3.1.15 to 2.5.*
`npm i -S  core-js@2.5.*`

**Comment by Shaif-Alam** [comment]
use this if facing  **Cannot find module 'core-js/library/fn/promise'**
npm i -S core-js@2.5.*
