### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by thorade** [AtomLinter/linter-htmlhint#27]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (C:\Users\mthorade\.atom\packages\linter\lib\main.coffee:57:8)
Package.activateNow (C:\Users\mthorade\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
<unknown> (C:\Users\mthorade\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30)
Package.measure (C:\Users\mthorade\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
Package.activate (C:\Users\mthorade\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
PackageManager.activatePackage (C:\Users\mthorade\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
```

**Comment by ikeagold** [comment]
:+1:

**Comment by opponitur** [comment]
+1

**Comment by q13** [comment]
+1

**Comment by preco21** [comment]
Same issue +1

**Comment by warpdesign** [comment]
:+1:

**Comment by alex-yamkov** [comment]
+1

**Comment by salvimateus** [comment]
+1

**Comment by miguelc1221** [comment]
+1

**Comment by kikelosada** [comment]
+1

**Comment by dereksnow** [comment]
+1

**Comment by phagoth** [comment]
+1

**Comment by salvimateus** [comment]
+1

**Comment by ApfelUser** [comment]
:+1:

**Comment by JoeNoPhoto** [comment]
+1

**Comment by williamtguerra** [comment]
+1

**Comment by williamtguerra** [comment]
+1

**Comment by Stephen304** [comment]
:+1:

**Comment by opponitur** [comment]
+1

**Comment by johnwebbcole** [comment]
If you can, please try the plugin from source and make sure it's still working for you.  There are instructions in the README.md file on testing from source.

**Comment by jaspervalero** [comment]
+1

**Comment by kikelosada** [comment]
This ok, eliminated the problem installing from source.

**Comment by aidanamavi** [comment]
+1

**Comment by Stephen304** [comment]
Has this been fixed in recent commits yet?

**Comment by johnwebbcole** [comment]
Yes, I'm waiting for some feedback on master.  Since the current version works (but has a depreciation warning) I'd like a few people to try it out first.

**Comment by JoeNoPhoto** [comment]
@johnwebbcole Not exactly sure what the README is telling me to do...

**Comment by thorade** [comment]
This is what I did to test the newest code:
Close Atom, then
```
cd ~/.atom/packages
rm linter-htmlhint
git clone git@github.com:AtomLinter/linter-htmlhint.git
```
Then restart Atom.

I get the following error, saying linter package cannot be found,
but I have it installed and other linter plugins work (I tried linter-chktex).

```

**Atom Version**: 1.0.3
**System**: MTHORADE-PC
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package, v0.1.0


### Stack Trace

Failed to activate the linter-htmlhint package

At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\mthorade\AppData\Local\atom\app-1.0.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.provideLinter (/C:/Users/mthorade/.atom/packages/linter-htmlhint/lib/init.coffee:34:17)
    at Package.module.exports.Package.activateServices (C:\Users\mthorade\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:374:69)
    at Package.module.exports.Package.activateNow (C:\Users\mthorade\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:246:16)
    at C:\Users\mthorade\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:224:30
    at Package.module.exports.Package.measure (C:\Users\mthorade\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15)

### Commands

### Config

{
  "core": {
    "disabledPackages": [
      "language-modelica",
      "language-r",
      "language-fortran"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}

### Installed Packages

coffee
# User
language-ini, v1.11.0
language-latex, v0.6.1
linter, v1.2.4
linter-htmlhint, v0.1.0
minimap, v4.12.1

# Dev
No dev packages
```

**Comment by thorade** [comment]
OK, sorry, after following the installation instructions in the ReadMe, the newest version works!

**Comment by scherii** [comment]
Tried it and it works as far as I can see :+1:

**Comment by Stephen304** [comment]
Now it's not only deprecated, it's removed. Is this going to be updated anytime soon?

**Comment by thorade** [comment]
Version 0.1.1 has fixed this issue for me. Thanks!
Closing the issue.
