### ISSUE TITLE
I have this error and does not correct it | Tengo este error y no se corregirlo

### ISSUE THREAD

**Issue by victorvace** [AtomLinter/linter-htmlhint#66]
Error: C:\Users\Víctor.atom\packages\linter-htmlhint\node_modules.bin\htmlhint:4 case uname in ^^^^

SyntaxError: Unexpected token case at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:413:25) at Object.Module._extensions..js (module.js:452:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:475:10) at startup (node.js:129:18) at node.js:981:3
Error: C:\Users\Víctor\.atom\packages\linter-htmlhint\node_modules\.bin\htmlhint:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3
    at parameters.exit (C:\Users\Víctor\.atom\packages\linter-csslint\node_modules\atom-linter\lib\helpers.js:75:20)
    at triggerExitCallback (C:\Users\Víctor\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Víctor\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by 1000ch** [comment]
dupe #65
