### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by despairblue** [AtomLinter/linter-htmlhint#9]
[Enter steps to reproduce below:]

1. open an html file

**What happens:**
* the file does not open and the error below is thrown
* retrying to open it opens the file in the currently opened buffer, see the screenshot: the file is open, but occupies the `Settings` pane instead of opening a new one.

![screenshot from 2015-03-26 14 49 13](https://cloud.githubusercontent.com/assets/927609/6847506/887ce28c-d3c7-11e4-8187-a8bbb7ae618e.png)

**Atom Version**: 0.188.0
**System**: linux 3.19.2-1-ARCH
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /usr/share/atom/resources/app/node_modules/q/q.js:128

TypeError: Cannot read property 'split' of undefined
  at findFile (/home/despairblue/.atom/packages/linter/lib/util.coffee:16:19)
  at LinterHtmlhint.setupHtmlHintRc (/home/despairblue/.atom/packages/linter-htmlhint/lib/linter-htmlhint.coffee:26:14)
  at __bind (/home/despairblue/.atom/packages/linter-htmlhint/lib/linter-htmlhint.coffee:1:1)
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:612:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:126:21)
  at new LinterHtmlhint (/home/despairblue/.atom/packages/linter-htmlhint/lib/linter-htmlhint.coffee:36:17)
  at LinterView.initLinters (/home/despairblue/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at new LinterView (/home/despairblue/.atom/packages/linter/lib/linter-view.coffee:33:6)
  at /home/despairblue/.atom/packages/linter/lib/init.coffee:88:24
  at /usr/share/atom/resources/app/src/workspace.js:287:16
  at /usr/share/atom/resources/app/src/workspace.js:344:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:375:27)
  at /usr/share/atom/resources/app/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:363:20)
  at Pane.addItem (/home/despairblue/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:60:19)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:336:14)
  at /usr/share/atom/resources/app/src/workspace.js:532:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:794:54)
  at Promise.then.Q.nextTick.self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:564:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -1:20.6 jumpy:toggle (atom-text-editor.editor.is-focused)
     -1:19.3 jumpy:e (atom-text-editor.editor.is-focused)
     -1:19.1 jumpy:y (atom-text-editor.editor.is-focused)
     -1:07.1 core:confirm (atom-text-editor.editor.mini)
     -0:07.7 jumpy:toggle (atom-text-editor.editor.is-focused)
     -0:06.6 jumpy:d (atom-text-editor.editor.is-focused)
     -0:06.5 jumpy:p (atom-text-editor.editor.is-focused)
     -0:05.6 core:close (atom-text-editor.editor.is-focused)
     -0:05.3 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -0:04.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:04.0 core:cancel (atom-text-editor.editor.mini)
     -0:03.6 fuzzy-finder:toggle-git-status-finder (div.settings-view.pane-item)
     -0:02.2 core:move-down (atom-text-editor.editor.mini)
     -0:01.7 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "linter-scspell",
      "navigate",
      "filetype-color",
      "atom-pair"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "linter": {
    "lintOnChange": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-alignment, v0.12.0
atom-color-highlight, v3.0.8
atom-ternjs, v0.5.6
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
block-cursor, v0.10.1
block-travel, v1.0.2
bug-report, v0.6.3
color-picker, v1.5.0
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v0.3.3
file-icons, v1.5.2
git-log, v0.3.0
go-plus, v3.3.1
grammar-token-limit, v0.1.1
highlight-selected, v0.9.1
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
jumpy, v2.0.4
keybinding-cheatsheet, v0.0.8
language-dockerfile, v0.1.0
language-fish-shell, v1.0.1
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.2
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-eslint, v0.5.0
linter-htmlhint, v0.0.9
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.8
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.2
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
open-last-project, v0.3.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
symbols-tree-view, v0.8.3
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.9.0
test-status, v0.28.3
travis-ci-status, v0.13.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by johnwebbcole** [comment]
I think this is related to AtomLinter/Linter#477.  I am getting the same error with .html files.  But other file types, like .js files, are throwing the error too.

**Comment by d4k0** [comment]
I'm getting the same error since I updated to Atom 0.188.0 (from 0.186.0). I already created an issue for this: https://github.com/AtomLinter/Linter/issues/480

**Comment by basarat** [comment]
The source of the error is that `htmlHintRcPath` is undefined from this call: 

```coffee
  setupHtmlHintRc: =>
    htmlHintRcPath = atom.config.get 'linter.linter-htmlhint.htmlhintRcFilePath'
    fileName = atom.config.get('linter.linter-htmlhint.htmlhintRcFileName') || '.htmlhintrc'
    config = findFile htmlHintRcPath, [fileName]
```
and in findFile we have `split` on an `undefined` `startDir` : 
```coffee
findFile = (startDir, name, parent = false, limit = null, aux_dirs = []) ->
  climb = startDir.split(path.sep)
```

Seems like the behavior of `atom.config.get 'linter.linter-htmlhint.htmlhintRcFilePath'` has changed between atom versions. Perhaps you got an empty string before. I'll send a PR with a fix.

**Comment by d4k0** [comment]
Thanks @basarat, this fixed the issue.
