### ISSUE TITLE
Failed to load the linter-htmlhint package

### ISSUE THREAD

**Issue by wataruoguchi** [AtomLinter/linter-htmlhint#97]
[Enter steps to reproduce below:]

1. Open a general React project by `$ atom .`
2. The error popped up

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package, v1.1.1

### Stack Trace

Failed to load the linter-htmlhint package

```
At Cannot find module 'consistent-env'

Error: Cannot find module 'consistent-env'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wataru/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/helpers.js:108:22)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wataru/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/index.js:140:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wataru/.atom/packages/linter-htmlhint/lib/index.js:3:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
highlight-column, v0.5.1
highlight-line, v0.11.1
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
linter, v1.11.4
linter-eslint, v7.1.3
linter-htmlhint, v1.1.1
linter-php, v1.2.0
linter-scss-lint, v2.5.1
minimap, v4.21.0
php-cs-fixer, v2.5.6
php-twig, v4.0.0
react, v0.15.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Can you try uninstalling and then installing `linter-htmlhint`? It looks like `apm` didn't properly install it.

**Comment by wataruoguchi** [comment]
Hi @Arcanemagus , thank you for the advice, it's resolved!
